site_name: E34M1 Documentation
site_description: Documentation for the EVA3 for Mercury One mod.
site_author: Jon Harper
site_url: https://jon-harper.github.io/E34M1
repo_url: https://github.com/jon-harper/E34M1
repo_name: "GitHub: jon-harper/E34M1"
edit_uri: ""
copyright: Copyright &copy; 2024 Jonathan Harper

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append: 
        - include/links.md
        - include/bom_links.md
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - navigation.top
    - navigation.sections
    - content.tooltips
  icon:
    logo: material/printer-3d-nozzle
  font:
    text: Noto Sans
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: deep orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: deep orange
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to match system light/dark mode

extra:
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/jonspaceharper
      name: "Support E34M1 using Ko-Fi!"
    - icon: material/home
      link: https://jon-harper.github.io/
      name: "jonspaceharper's Homepage"
  meta: 
    bom: assets/e34m1.yaml
    bom_template_str: v2
extra_css:
  - assets/stylesheets/extra.css

plugins:
  - git-revision-date-localized:
      type: custom
      custom_format: "%Y-%m-%d %H:%M:%S %z (UTC)"
      timezone: America/Detroit
  - search
  - macros:
      module_name: "src"
      include_dir: include
  - social:
      enabled: !ENV [CI, false]
      
nav:
  - index.md
  - Getting Started:
    - guide.md
    - tour.md
  - Module Reference:
    - modules/index.md
    - Core Modules:
      - modules/front.md
      - modules/top.md
      - modules/bottom.md
      - modules/rear.md
      - modules/abl.md
    - Universal Modules:
      - modules/hotend.md
      - modules/drive.md
    - Other Modules:
      - modules/stop_block.md
      - modules/pcb_mounts.md
      - modules/other.md
  - Assembly:
    - assembly/index.md
    - Guide:
      - assembly/first.md
      - assembly/core.md
      - assembly/fan.md
      - assembly/belts.md
      - assembly/hotend.md
      - assembly/drive.md
      - assembly/abl.md
      - assembly/final.md
  - Resources:
    - sourcing.md
    - changelog.md
  